### ISSUE TITLE
Display items in random page OR have a link for random items?

### ISSUE THREAD

**Issue by addshore** [wbstack/mediawiki#27]

**Comment by GreenReaper** [comment]
I tried on Wikidata and random item is in fact random page (and does show you items there), so perhaps it might be suitable for enable for that namespace. It is also the "Random" in the mobile skin.

I don't know if this is something that should be a config option eventually, though. Perhaps if more options for namespace customisation are added?

(For a truly new user it is not all that clear how to get a list of existing items or properties, either, as there is no sidebar option for it. If you know about MediaWiki you might think to go to per-namespace all pages.)

**Comment by addshore** [comment]
> I tried on Wikidata and random item is in fact random page (and does show you items there), so perhaps it might be suitable for enable for that namespace. It is also the "Random" in the mobile skin.

Indeed, so for Wikidata this is the case as the Items and in the main namespace.
So the equivalent here I believe would be setting NS 120 to also be a content namespace.

https://www.mediawiki.org/wiki/Manual:$wgContentNamespaces

This is something fixable in wbstack, but also probably something that should be upstreamed into the default functionality of Wikibase

**Comment by GreenReaper** [comment]
I think the change is suitable for WBStack, because it is focused on the Wikibase use of MediaWiki.

Whether it is suitable for Wikibase in general may depend on whether people are integrating it into another site, for which pages are the primary means of user interaction to view data which has been entered as items, or for which such items are only a portion of content. Perhaps it is more appropriate for the Docker release, which might be expected to act as a standalone database, than the extension?

**Comment by addshore** [comment]
This is now deployed
