### ISSUE TITLE
Enable / consider multi line string data type for Wikibase

### ISSUE THREAD

**Issue by addshore** [wbstack/mediawiki#57]
https://twitter.com/nyuriks/status/1378091689626247169

![image](https://user-images.githubusercontent.com/3308769/113454515-53192600-9400-11eb-8ea2-3b0995798af9.png)

https://github.com/nyurik/ThatSrc

**Comment by GreenReaper** [comment]
Code would need a review, the comments don't give me confidence. For example [this file claims](https://github.com/nyurik/ThatSrc/blob/master/includes/HtmlMultilineTextFormatter.php) to a) be authored by Daniel Kinzler and b) format a URL, while [the hook onWikibaseRepoDataTypes()](https://github.com/nyurik/ThatSrc/blob/3e039311504eb82f8c5c488a457b9e376b5cf7e3/includes/ThatSrc.hooks.php#L72) has "Add Datatype "Math" to the Wikibase Repository". There are also [some FIXME and HACK notes](https://github.com/nyurik/ThatSrc/blob/master/modules/MultilineTextValue.js) which could need addressing. And [permitting 1M characters by default](https://github.com/nyurik/ThatSrc/blob/3e039311504eb82f8c5c488a457b9e376b5cf7e3/includes/ThatSrc.hooks.php#L41) seems... excessive?

Perhaps they have an example of it in use already? I see no hits on WikiApiary for extension "[ThatSrc](https://github.com/nyurik/ThatSrc/blob/master/extension.json)" (version 0.0.1 or otherwise). Using WBStack for WB extension testing _might_ be a worthwhile use, but also the sort of thing that might need to be sandboxed.

**Comment by addshore** [comment]
It'd be great for the extension to have a better name.
https://github.com/nyurik/ThatSrc/issues/1

I scanned the code and it looks fine to give it a go including it.
Though I will not enable it by default on sites right now, but will enable it where requested by @nyurik so that he can try it out etc.

**Comment by addshore** [comment]
Added, but off by default for now, please poke me if you want it enabled on a specific wiki

**Comment by nyurik** [comment]
Thanks for the ping and the review!  I agree it needs a better name -- I was hoping to get some feedback in its initial phase. One thing I wasn't sure about -- should this be a project-specific extension (implement all features needed for my project), or a feature-specific extension (implement just the multiline strings, and if i need some other functionality that requires code modifications, do that in a separate project). At first i began implementing it as first option, but it mostly ended up fulfilling just one ask, thus the naming problem. 

@addshore please add it to https://datasrc.wiki.opencura.com/

**Comment by addshore** [comment]
I think the second choice would be best, having something generic for multi line strings, and anything extra built on top of that.
I'll go and add it to that site now!
