### ISSUE TITLE
Add WikibaseEdtf data type

### ISSUE THREAD

**Issue by addshore** [wbstack/mediawiki#60]
https://github.com/ProfessionalWiki/WikibaseEdtf

Requested on telegram

**Comment by addshore** [comment]
![image](https://user-images.githubusercontent.com/3308769/116149504-22b06900-a6da-11eb-9859-7961121fe518.png)

**Comment by addshore** [comment]
Per https://github.com/ProfessionalWiki/WikibaseEdtf/issues/3 and https://github.com/ProfessionalWiki/WikibaseEdtf/issues/13 currently being in discussion I might backtrack and hide this data type behind a feature flag for now until the RDF output is stable / decided.

**Comment by GreenReaper** [comment]
This is great, as it may eliminate the need for qualifier hacks to match a start time with an end time - I was wondering about compatibility with other date types, but it looks like the issue above addresses that.

(Perhaps longer-term it might generate a compatibility start time and end time property so that it could be matched to shapes that require them? I guess the shapes could be modified to accept one or the other.)

**Comment by GreenReaper** [comment]
It's working, however I got an internal server error after ~5 seconds by putting in e.g. [2001,Y3278E4..Y3389E4]. It is presumably generating this list internally as well as externally via the dual client/server rendering, and timing out or exceeding a size limit.

There is no apparent limit on the range, and when specified in this manner, the human format lists each year individually, e.g. 
> (One of these: 33780000, 33780001, 33780002, 33780003, 33780004, 33780005, 3378000

for the slightly-less-extensive `[Y3378E4..Y3389E4]`, for which the gzipped API response is 223.90 KB (1.05 MB decompressed).

I guess this is more a bug for their repo, but perhaps also something to consider for whether/when to enable this by default.

**Comment by GreenReaper** [comment]
1.2.0 is out, using [version 2.0 of EDTF](https://github.com/ProfessionalWiki/EDTF/commits/2.0.0), said to [resolve the above issue, and improve humanization and validation](https://github.com/ProfessionalWiki/EDTF/blob/070d4be1a1a2dfbabfacc7d8f5e47092415e78e4/README.md#release-notes).

Their tests run on 1.36 and 1.35. Master breaks due to [removal of `WikibaseClient::getDefaultInstance`](https://phabricator.wikimedia.org/T280765).

**Comment by addshore** [comment]
> 1.2.0 is out, using [version 2.0 of EDTF](https://github.com/ProfessionalWiki/EDTF/commits/2.0.0), said to [resolve the above issue, and improve humanization and validation](https://github.com/ProfessionalWiki/EDTF/blob/070d4be1a1a2dfbabfacc7d8f5e47092415e78e4/README.md#release-notes).
> 
> Their tests run on 1.36 and 1.35. Master breaks due to [removal of `WikibaseClient::getDefaultInstance`](https://phabricator.wikimedia.org/T280765).

Thanks for the poke, it looks like it would make sense to try and get this update out on wbstack! :)

**Comment by GreenReaper** [comment]
Indeed - it looks like the only updates since then have been localisation additions/fixes to the library portion.
